// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxrlfkrqhtepayiwistb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4cmxma3JxaHRlcGF5aXdpc3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjgwNDUsImV4cCI6MjA2NTkwNDA0NX0.UZKwBQiXtgqpOnlTA6gXrhL4h0vZ3FcSauazWunMAIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);